/* List homepage in the page sitemap only (not page and post sitemap both, which happened with the auto-generated by yoast plugin) */

add_filter( 'wpseo_sitemap_post_type_archive_link', 'custom_wpseo_post_type_archive_link', 10, 2 );

function custom_wpseo_post_type_archive_link( $link, $post_type ) {
    if ( $post_type === 'post' ) {
        return false;        
    }
    return $link;
}

add_filter( 'wpseo_sitemap_entry', 'remove_homepage_from_post_sitemap', 10, 3 );

function remove_homepage_from_post_sitemap( $url, $post, $context ) {
    if ( $context === 'post' && $post->ID === get_option( 'page_on_front' ) ) {
        return false;
    }
    return $url;
}
